-- TimeCheck SQLite schema

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT NOT NULL UNIQUE,
    PWD TEXT NOT NULL,
    NAME TEXT NOT NULL,
    DEPARTMENT TEXT,
    TEAM TEXT,
    POSITION TEXT,
    ROLE TEXT NOT NULL DEFAULT 'USER',
    CREATED_AT TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATED_AT TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    LAST_ACCESS TEXT
);

CREATE TABLE IF NOT EXISTS WORK (
    WORK_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    WORK_DATE TEXT NOT NULL,
    RAW_START TEXT,
    RAW_END TEXT,
    MAIN_START TEXT,
    MAIN_END TEXT,
    BASE INTEGER NOT NULL DEFAULT 0,
    MAIN INTEGER NOT NULL DEFAULT 0,
    EXTRA_1 INTEGER NOT NULL DEFAULT 0,
    EXTRA_2 INTEGER NOT NULL DEFAULT 0,
    OT_START TEXT,
    OT_END TEXT,
    IS_OT INTEGER NOT NULL DEFAULT 0,
    DAY_TYPE TEXT NOT NULL DEFAULT 'NOM',
    LATE_IN TEXT,
    EARLY_OUT TEXT,
    REMARK TEXT,
    CREATED_AT TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    UPDATED_AT TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    CONSTRAINT UK_WORK_USER_DATE UNIQUE (USER_ID, WORK_DATE),
    CONSTRAINT CK_WORK_DAY_TYPE CHECK (DAY_TYPE IN ('NOM', 'AM', 'PM', 'MON', 'ANN', 'HOL'))
);

CREATE INDEX IF NOT EXISTS IDX_WORK_WORK_DATE ON WORK (WORK_DATE);
CREATE INDEX IF NOT EXISTS IDX_WORK_USER_DATE ON WORK (USER_ID, WORK_DATE);